FROM ubuntu:20.04 as base
RUN apt update && apt install tzdata -y
ENV TZ="America/New_York"
RUN apt-get install -y build-essential pkg-config libdlib-dev libopenblas-dev libgfortran-8-dev libjpeg-turbo8-dev
ADD docker/dlib-1.pc /usr/local/lib/pkgconfig/
RUN pkg-config --cflags  -- dlib-1
