# This script is provided by github.com/bool64/dev.

# This script uploads application binaries as GitHub release assets.
name: release-assets
on:
  pull_request:
  release:
    types:
      - created
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    name: Upload Release Assets
    runs-on: ubuntu-latest
    steps:
      - name: Install Go stable
        if: env.GO_VERSION != 'tip'
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build artifacts
        run: |
          make docker-build
          docker run -v $PWD:/opt/mount --rm --entrypoint cp vearutop/faces /bin/faces /opt/mount/faces
          tar zcvf ./linux_amd64.tar.gz ./faces
      - name: Upload linux_amd64.tar.gz
        if: hashFiles('linux_amd64.tar.gz') != ''
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./linux_amd64.tar.gz
          asset_name: linux_amd64.tar.gz
          asset_content_type: application/tar+gzip
